
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/armon/go-proxyproto"
  revision = "3daa90aec0039a806299b9078f4422fee950f33c"

[[constraint]]
  revision = "ebf008572634916f3a9433d9471a0cd3f68fc772"
  name = "github.com/bshuster-repo/logrus-logstash-hook"

[[constraint]]
  revision = "cc3942e537b1ab00de92d348c40acbfa6565d20f"
  name = "github.com/buger/goterm"

[[constraint]]
  name = "github.com/codegangsta/cli"
  version = "1.19.1"

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "3.3.8"

[[constraint]]
  revision = "757bef944d0f21880861c2dd9c871ca543023cba"
  name = "github.com/gorilla/mux"

[[constraint]]
  revision = "2b3c4565aafdcd40c8069e50de08ac5379787943"
  name = "github.com/mailgun/metrics"

[[constraint]]
  branch = "master"
  name = "github.com/mailgun/timetools"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  revision = "adbef6bedf021985587c3c18c9d4b84b2d78f67c"
  name = "github.com/vulcand/oxy"

[[constraint]]
  branch = "master"
  name = "github.com/vulcand/route"

[[constraint]]
  revision = "76eec36fa14229c4b25bb894c2d0e591527af429"
  name = "golang.org/x/crypto"

[[constraint]]
  revision = "45e771701b814666a7eb299e6c7a57d0b1799e91"
  name = "golang.org/x/net"

[[constraint]]
  branch = "v1"
  name = "gopkg.in/check.v1"

[prune]
  go-tests = true
  unused-packages = true
